### ISSUE TITLE
sdf's BeamStep Inflexible to new stations

### ISSUE THREAD

**Issue by ctaylor-physics** [lwa-project/lsl#69]
It appears that the BeamStep class is not flexible in it's current state to handle LWA stations having less that 520 inputs. I tried making a session using fringeSDF.py from the commissioning repo and the ssmif from the NA station, but it threw the following errors:
```
>>> python3 fringeSDF_dev.py ~/lsl/lsl/data/lwana-ssmif.txt 2024/06/20 18:00:00 -d 63 -r 39 -o fringe_test3.sdf

Number of bad stands:    16
Number of bad FEEs:       0
---------------------------
Total number bad inputs:  16
 
Setting all delays to zero
128
Setting gains for dipoles 63 and 39
[1385115] Validating session 1
[1385115] Validating observation 1
[1385115] Validating step 1
[1385115] Error: Specified delay list had the wrong number of antennas
[1385115] Error: Specified gain list had the wrong number of stands
Traceback (most recent call last):
  File "fringeSDF_dev.py", line 242, in <module>
    main(args)
  File "fringeSDF_dev.py", line 198, in main
    project.render(verbose=True)
  File "/home/ctaylor/.local/lib/python3.8/site-packages/lsl/common/sdf.py", line 537, in render
    raise RuntimeError("Invalid session/observation parameters.  Aborting.")
RuntimeError: Invalid session/observation parameters.  Aborting.

```

From here the validation errors occur in the stepped observing component to this observation, particularly in these last shape comparison tests in /lsl/common/sdf:

https://github.com/lwa-project/lsl/blob/78f53796e8258263454d2e3c3ff3ee4d31f0eac8/lsl/common/sdf.py#L2031

For using the NA, it falls out of the SV alternative cases. Not having 520 inputs, like LWA1 as the class is hard coded for, results in a couple errors on the delays+gains. From this info, it appears this section of lsl needs to get the NA/mini-station flexibility update or maybe it is defunct if it's still hard coded for LWA1.

**Comment by jaycedowell** [comment]
`lsl.common.sdf` is LWA1/DP specific.  What if you use `sdfNDP` from the lwana branch or even `sdfADP`?

**Comment by ctaylor-physics** [comment]
The code runs fine with LWA1 or LWA-SV specific inputs fine from what I can tell. I tried with both the sdfNDP and sdfADP options using the lwana-ssmif, but I still am getting the same error mode. Seems to think that I have the wrong number of antennas/stands still, strange that I still get the "Error: Specified delay list had the wrong number of antennas" message even though it doesn't appear in sdfNDP. I suspected it is sneaking back to common/sdf to access the Stepped mode, and maybe that validates in the wrong, but sdfADP works fine.

I also tried to hack one of the output files from LWA1 inputs, but the dry run on NA did not like it. Here is the readout from that dry run schedule even though it's not much, the rest of the entries from this printout don't look alarming to me. I can post the rest if that is needed though. 

```[201/72776] FATAL: TPSS_PL_KEYWORD_MISMATCH```

**Comment by jaycedowell** [comment]
Yeah, post the rest.  That error message needs some context.

**Comment by ctaylor-physics** [comment]
Ok here is the printout from my hack attempt. I naively assumed that since I was interested in antennas less than 64, it wouldn't be too much trouble to trim off the excess made by using LWA1 as the basis. So 128 delays and 64 sets of gains, instead of 520/260, although from this we didn't even make it to checking gains. 

```
op1@lwana-tp:~/MCS/tp$ ./tpss 240621/DT005_fringe_na_hack.sdf 4 0 mbox
[201/72776] Input: sdf='240621/DT005_fringe_na_hack.sdf'
[201/72776] Input: max_phase=4
[201/72776] Input: bIgnoreActualTime=0
[201/72776] Input: mbox='mbox'
[201/72776] *********************************************************
[201/72776] *** Phase 1: Reading/Parsing Session Defintion File *****
[201/72776] *********************************************************
[201/72776] PI_ID='89'
[201/72776] PI_NAME='Craig Taylor'
[201/72776] PROJECT_ID='FRINGSDF'
[201/72776] PROJECT_TITLE='single dipoles'
[201/72776] PROJECT_REMPI='None provided'
[201/72776] PROJECT_REMPO='None'
[201/72776] SESSION_ID='123'...converts to 123
[201/72776] SESSION_TITLE='fringeSDF.py Session'
[201/72776] SESSION_REMPI='ucfuser:ctaylor'
[201/72776] SESSION_REMPO='Requested data return method is UCF'
[201/72776] SESSION_DRX_BEAM='2'...converts to 2
[201/72776] OBS_ID='1'...converts to 1
[201/72776] === Parsing Defined Observation #1 ===
[201/72776] OBS_TITLE='fringeSDF.py Target'
[201/72776] OBS_TARGET='Custom'
[201/72776] OBS_REMPI='None provided'
[201/72776] OBS_REMPO='Estimated data volume for this observation is 264.91 GB'
[201/72776] OBS_START_MJD='60482'...converts to 60482
[201/72776] OBS_START_MPM='28800000'...converts to 28800000
[201/72776] OBS_START='UTC 2024/06/20 18:00:00.000000'
[201/72776] OBS_DUR='600000'...converts to 600000
[201/72776] OBS_DUR+='0:10:00.000'
[201/72776] OBS_MODE='STEPPED'...converts to 'STEPPED'
[201/72776] OBS_BW='7'...converts to 7
[201/72776] OBS_BW+='19.600 MHz'
[201/72776] OBS_STP_N='1'...converts to 1
[201/72776] OBS_STP_RADEC='0'...converts to 0
[201/72776] --- Parsing Defined Step #1 of Observation #1 ---
[201/72776] OBS_STP_C1[1]='90.000000000'...converts to 90.000000
[201/72776] OBS_STP_C2[1]='+90.000000000'...converts to 90.000000
[201/72776] OBS_STP_T[1]='3600000'...converts to 3600000
[201/72776] OBS_STP_FREQ1[1]='830506431'...converts to 830506431
[201/72776] OBS_STP_FREQ1+[1]='37.899999990 MHz'
[201/72776] OBS_STP_FREQ2[1]='1621569285'...converts to 1621569285
[201/72776] OBS_STP_FREQ2+[1]='73.999999990 MHz'
[201/72776] OBS_STP_B[1]='SPEC_DELAYS_GAINS'...converts to 'SPEC_DELAYS_GAINS'
[201/72776] OBS_BEAM_DELAY[1][1]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][2]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][3]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][4]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][5]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][6]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][7]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][8]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][9]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][10]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][11]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][12]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][13]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][14]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][15]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][16]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][17]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][18]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][19]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][20]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][21]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][22]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][23]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][24]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][25]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][26]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][27]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][28]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][29]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][30]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][31]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][32]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][33]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][34]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][35]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][36]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][37]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][38]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][39]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][40]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][41]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][42]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][43]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][44]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][45]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][46]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][47]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][48]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][49]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][50]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][51]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][52]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][53]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][54]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][55]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][56]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][57]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][58]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][59]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][60]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][61]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][62]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][63]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][64]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][65]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][66]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][67]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][68]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][69]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][70]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][71]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][72]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][73]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][74]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][75]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][76]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][77]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][78]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][79]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][80]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][81]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][82]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][83]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][84]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][85]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][86]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][87]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][88]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][89]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][90]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][91]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][92]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][93]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][94]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][95]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][96]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][97]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][98]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][99]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][100]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][101]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][102]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][103]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][104]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][105]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][106]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][107]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][108]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][109]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][110]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][111]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][112]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][113]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][114]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][115]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][116]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][117]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][118]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][119]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][120]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][121]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][122]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][123]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][124]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][125]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][126]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][127]='0'...converts to 0
[201/72776] OBS_BEAM_DELAY[1][128]='0'...converts to 0
[201/72776] FATAL: TPSS_PL_KEYWORD_MISMATCH
```

**Comment by jaycedowell** [comment]
Ah, ok.  It really want there to be all 256 antennas filled for OBS_BEAM_DELAY and OBS_BEAM_GAIN.

**Comment by jaycedowell** [comment]
We can either address this here in `sdfNDP` or over at https://github.com/lwa-project/monitor_and_control.  The options:
 * `sdfNDP` - We need to make sure that it always fills out all 256 antennas even if there are only 64 given via a SSMIF.
 * MCS - We would need to update `tpss` so that for NDP stations it would set everything to zero for OBS_BEAM_DELAY/GAIN and then fill what it could.

Of those the changes to `sdfNDP` are probably easier.  @ctaylor-physics do you want to take a shot at a PR to implement that?

**Comment by ctaylor-physics** [comment]
Sure, I'll take a whack at it. I will make some changes to sdfNDP to propagate the gains/delays out to 256 and submit a PR.

**Comment by ctaylor-physics** [comment]
How do we feel about this as a fix? It will pad out the sizes of 'delays' and 'gains' before heading into the sdfNDP code. 
https://github.com/lwa-project/commissioning/pull/16#issue-2367302285

**Comment by jaycedowell** [comment]
I was thinking that we should patch `sdfNDP` directly.

**Comment by ctaylor-physics** [comment]
Yes, with the previous two commits here and adding in a case for LWA-NA, fringeSDF.py will write out files without erroring out. They appear to be correct in comparison with the files I previously created with LWA1. 

The file written was also able to be scheduled at NA, which was an issue for the hacked file I tested before.
